version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: store-management-api
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  storemanagement.db:
    image: postgres:latest
    container_name: storemanagement-db
    environment:
      - POSTGRES_DB=storemanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  otherstoremanagement.db:
    image: postgres:latest
    container_name: otherstoremanagement-db
    environment:
      - POSTGRES_DB=storemanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5433:5432